OnlineStore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OnlineStore.ViewModel;
using System.Data;
using System.Net.Http.Headers;
using System.Text;

namespace OnlineStore.Controllers
{
    public class ProductController:Controller
    {
        private readonly HttpClient client;
        private readonly IConfiguration Configuration;
        public ProductController(HttpClient client, IConfiguration Configuration)
        {
            this.client = client;
            this.Configuration = Configuration;
        }
        //[Authorize]
        public async Task<IActionResult> List(int? pageNumber, int? pageSize)
        {
            var apiurl = Configuration["ApiSetting:ApiUrl"];
            //var token = HttpContext.Session.GetString("Token");

            //client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            try
            {
                var response = await client.GetAsync(apiurl + "api/Product/get-product-list");

                if (!response.IsSuccessStatusCode)
                {
                    var msg = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<ApiErrorViewModel>(msg);
                    ModelState.AddModelError("error", result.Message);
                    return View(new List<ProductViewModel>());
                }
                else
                {
                    var res = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<List<ProductViewModel>>(res);
                    //var pagResult = PaginatedList<ProductViewModel>.CreateFromLinqQueryable(result.AsQueryable(), pageNumber ?? 1, pageSize ?? 20);
                    return View(result);

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("ERRRORRRR : ", ex.Message);
                return View(new List<ProductViewModel>());
            }
        }
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Create()
        {
            return View(new ProductViewModel());
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var apiurl = Configuration["ApiSetting:ApiUrl"];
            var token = HttpContext.Session.GetString("Token");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await client.GetAsync(apiurl + "api/Product/get-product?Id="+ id);
            if (!response.IsSuccessStatusCode)
            {
                var msg = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<ApiErrorViewModel>(msg);
                ModelState.AddModelError("error", result.Message);
                return View(new ProductViewModel());
            }
            else
            {
                var msg = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<ProductViewModel>(msg);
                return View(result); ;
            }
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([FromForm] ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var apiurl = Configuration["ApiSetting:ApiUrl"];
                var token = HttpContext.Session.GetString("Token");
                model.Id = Guid.NewGuid();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                string jsonData = JsonConvert.SerializeObject(model);
                var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                var response = await client.PostAsync(apiurl + "api/Product/create-product", content);
                if (!response.IsSuccessStatusCode)
                {
                    var msg = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<ApiErrorViewModel>(msg);
                    ModelState.AddModelError("error", result.Message);
                    return View(model);
                }
                else {
                    return RedirectToAction("List");
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit([FromForm] ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var apiurl = Configuration["ApiSetting:ApiUrl"];
                string jsonData = JsonConvert.SerializeObject(model);
                var token = HttpContext.Session.GetString("Token");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
                var response = await client.PutAsync(apiurl + "api/Product/update-product", content);
                if (!response.IsSuccessStatusCode)
                {
                    var msg = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<ApiErrorViewModel>(msg);
                    ModelState.AddModelError("error", result.Message);
                    return View(model);
                }
                else
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var apiurl = Configuration["ApiSetting:ApiUrl"];
            var token = HttpContext.Session.GetString("Token");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var response = await client.DeleteAsync(apiurl + "api/Product/delete-product?Id=" + id);
            if (!response.IsSuccessStatusCode)
            {
                var msg = await response.Content.ReadAsStringAsync();
                return RedirectToAction("List");
            }
            else
            {
                var msg = await response.Content.ReadAsStringAsync();
                return RedirectToAction("List");
            }
        }
    }
}

OnlineStore/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OnlineStore.ViewModel;
using System.IdentityModel.Tokens.Jwt;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;

namespace OnlineStore.Controllers
{
    public class UsersController : Controller
    {
        private readonly HttpClient client;
        private readonly IConfiguration Configuration;
        public UsersController(HttpClient client, IConfiguration Configuration)
        {
            this.client = client;
            this.Configuration = Configuration;
        }
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> List(int? pageNumber, int? pageSize)
        {
            var apiurl = Configuration["ApiSetting:ApiUrl"];

            var model = new { pageNumber = pageNumber, pageSize = pageSize };
            string jsonData = JsonConvert.SerializeObject(model);

            var token=HttpContext.Session.GetString("Token");

            var content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await client.PostAsync(apiurl + "api/user/user-list", content);
            if (!response.IsSuccessStatusCode)
            {
                var msg = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<ApiErrorViewModel>(msg);
                ModelState.AddModelError("error", result.Message);
                return View();
            }
            else
            {
                var res = await response.Content.ReadAsStringAsync();
                var result = JsonConvert.DeserializeObject<List<UsersViewModel>>(res);
                var pagResult=PaginatedList<UsersViewModel>.CreateFromLinqQueryable(result.AsQueryable(), pageNumber ?? 1,pageSize ?? 10);
                return View(pagResult);
            }
            return View();
        }
    }
}

OnlineStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Product List</a>
                        </li>
                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="List">Users List</a>
                            </li>
                        }
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - OnlineStore @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>